### ISSUE TITLE
Blurry character art

### ISSUE THREAD

**Issue by skvrahul** [ImperialOctopus/avalon-cards#5]
The character art is quite blurry in the exported PDF.
My guess is that it's perhaps due to Illustrator's rasterization step before exporting the PDF.

**Comment by ImperialOctopus** [comment]
That's the cards PDF from the v1.0.0 release? The art doesn't look blurry at all in either Chrome or Acrobat Reader on my computer...

**Comment by skvrahul** [comment]
Whoops. My bad. Looks like its just with the PDF reader I was using. Sorry about that!
